name: CD - Kubernetes (Kind)

on:
  workflow_run:
    workflows: ["CI - Build and Push Image"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1
      - name: Pull image
        run: docker pull 221110019/devops-laravel:${{ github.event.workflow_run.head_sha }}
      - name: Load image
        run: kind load docker-image 221110019/devops-laravel:${{ github.event.workflow_run.head_sha }}
      - name: Deploy
        run: |
          kubectl apply -f kubernetes/
          kubectl set image deployment/laravel-deployment laravel=221110019/devops-laravel:${{ github.event.workflow_run.head_sha }}
          kubectl rollout status deployment/laravel-deployment --timeout=120s
      - name: Cleanup
        run: |
          docker image prune -af

